Module6 task2
htmlacademy-react/490939-six-cities-6 pull request #11
Opened 2021-03-09 21:26 UTC by akzhar

2021-03-11 18:32 UTC, vatokato requested changes
В целом хорошо. Кроме формы, уж слишком она какая то 'не реактовская' получилась... смотрел твой код и вспоминал времена, когда писал js на jQuery :D

2021-03-11 18:32 UTC, vatokato commented on src/components/comment-form/comment-form.jsx
> +        child.disabled = bool;
Задизабливание через перебор дочерних элементов ДОМа - выглядит очень странно.

Правильно было бы ввести буль `disabled` через `useState` и в коде уже указывать задизабленность: `<button ... disabled={disabled}>Submit</button>`

2021-03-11 18:32 UTC, vatokato commented on src/components/comment-form/comment-form.jsx
> +    setRating(null);
раз ты везде пользуешься `ref` и данные берешь из `event.target`, то может быть тебе вообще не нужно держать данные в стейте? форму можно очистить с помощью `form.reset()` (https://developer.mozilla.org/ru/docs/Web/API/HTMLFormElement/reset)

2021-03-11 18:32 UTC, vatokato commented on src/components/login-screen/login-screen.jsx
> +        history.push(AppRoute.MAIN);
это плохая практика. лучше делать редирект либо через компонент `<Redirect />`, а лучше через экшен `Action.RedirectTo('/')` - это должно быть в уроке где делали редирект.

Все движения должны быть по максимуму проходить через редакс, чтобы легче блыло отлаживать код.

2021-03-14 18:32 UTC, akzhar commented on src/components/comment-form/comment-form.jsx
> +        child.disabled = bool;
Увлекся)
Исправлено

2021-03-14 21:21 UTC, akzhar commented on src/components/comment-form/comment-form.jsx
> +    setRating(null);
Убрал данные из стейта, кроме булева значения `disabled` для элементов формы.
Можно отказаться от стейта совсем, но тогда нужен цикл по input'ам rating.

2021-03-14 21:37 UTC, akzhar commented on src/components/login-screen/login-screen.jsx
> +        history.push(AppRoute.MAIN);
Ок. Я думал, что в через редакс только экшены, относящиеся так или иначе к стейту приложения. Получается, если пускать через редакс другие экшены, то и правда: проще отлаживать. Возьму на заметку! Спасибо.

2021-03-14 21:37 UTC, akzhar commented on src/components/login-screen/login-screen.jsx
> +        history.push(AppRoute.MAIN);
Исправил.

2021-03-15 15:51 UTC, merged