Module7 task1
htmlacademy-react/490939-six-cities-6 pull request #13
Opened 2021-03-16 15:09 UTC by akzhar

2021-03-16 17:00 UTC, vatokato requested changes
По оптимизации вопров нет, все отлично

Но несколько замечаний все таки имеется

2021-03-16 17:00 UTC, vatokato commented on src/store/reducer-offers.js
> +      return {...state, all: action.payload};
лучше `items`, а не `all`

не критично

2021-03-17 10:01 UTC, merged

2021-03-17 15:58 UTC, akzhar commented on src/store/reducer-history.js
> +};
Да, согласен

2021-03-17 16:19 UTC, akzhar commented on src/store/reducer.js
>  };
Разнес `initialState` по файлам редьюсеров

2021-03-17 16:47 UTC, akzhar commented on src/store/reducer-offers.js
> +      return {...state, all: action.payload};
Согласен, переименовал

2021-03-17 17:37 UTC, akzhar commented on src/components/main-screen-map/main-screen-map.jsx
> +  }, [activeCity]);
Добавил использование `reselect`