Module1 task3
htmlacademy-react/490939-six-cities-6 pull request #3
Opened 2021-02-04 21:33 UTC by akzhar

2021-02-05 13:55 UTC, vatokato requested changes
В целом все отлично, молодец, хорошее начало.

Несколько моментов по ревью, которые мне очень сильно облегчат работу:

* Прошу отвечать на все мои комментарии в ревью, даже если это будет банальное: сделано, исправлено и т.д.
* `не критично` в комментарии означает, что это замечание править не обязательно, на твое усмотрение.
* Резолвить самостоятельно можно только не критичные замечания.

Заранее спасиб :)

2021-02-05 13:55 UTC, vatokato commented on src/components/offer-card/offer-card.jsx
> +const OfferCard = (props) => {
можно использовать деструктуризацию в аргументах: 
`const OfferCard = ({isPremium, header, costEuro}) => {`
иногда это удобно.

не критично.

2021-02-05 13:55 UTC, vatokato commented on src/components/main-screen/main-screen.jsx
> +  offers: PropTypes.arrayOf(PropTypes.object).isRequired
Критерий [Д25](https://up.htmlacademy.ru/react/6/criteries#d25):

Нужно указывать подбробно. Либо вынести в отдельный файл (лучший вариант), либо продублировать

2021-02-05 13:55 UTC, vatokato commented on src/components/app/app.jsx
> +  offers: [
1. все таки это не настройки, а данные. Лучше вынести их в отдельную переменную. 
2. по заданию 8 их нужно описать не в этом файле )

2021-02-05 13:55 UTC, vatokato commented on src/components/app/app.jsx
> +const SETTINGS = {
Настройки нужно передавать из index.js

2021-02-05 14:31 UTC, akzhar commented on src/components/offer-card/offer-card.jsx
> +const OfferCard = (props) => {
сделано

2021-02-05 14:50 UTC, akzhar commented on src/components/main-screen/main-screen.jsx
> +  offers: PropTypes.arrayOf(PropTypes.object).isRequired
вынес в отдельный файл

2021-02-05 15:10 UTC, akzhar commented on src/components/app/app.jsx
> +  offers: [
вынес данные в отдельный json файл

2021-02-06 11:33 UTC, vatokato commented on src/prop-types/prop-types.jsx
> +export const offerShape = {
немного не верно.

если это `offerShape`, то прям тут и нужно делать

```
export const offerShape = PropTypes.shape({
  isPremium: PropTypes.bool.isRequired,
  costEuro: PropTypes.number.isRequired,
  header: PropTypes.string.isRequired
})
```
и импортировать уже шейп, а у тебя это объект с пропс тайпами )

2021-02-06 11:34 UTC, vatokato commented on src/index.js
> +    <App data={offers}/>,
я бы назвал пропс `offers`, а не дата. 

не критично

2021-02-06 15:55 UTC, akzhar commented on src/index.js
> +    <App data={offers}/>,
переименовал

2021-02-06 16:05 UTC, akzhar commented on src/prop-types/prop-types.jsx
> +export const offerShape = {
Хотел повысить таким образом читабельность внутри компонентов, использующих этот PropTypes.

Мне казалось так более наглядно что есть что.

Main Screen:
`MainScreen.propTypes = PropTypes.arrayOf(PropTypes.shape(offerShape)).isRequired;`

Offer Card:
`OfferCard.propTypes = PropTypes.shape(offerShape).isRequired;`

Но исправил, и соглашусь, что исправленный вариант нправильнее и нагляднее.

2021-02-06 17:15 UTC, merged