Module3 task1
htmlacademy-react/490939-six-cities-6 pull request #5
Opened 2021-02-14 10:58 UTC by akzhar

2021-02-15 07:05 UTC, vatokato requested changes
В целом хорошо.

Если что-то непонятно - пиши сюда или в телегу.
Если что-то ты сделал так как на лекции, а я прошу переделать, то тоже напиши плиз (не смотрел последний лайв), я посмотрю и приму другое решение

2021-02-15 09:41 UTC, akzhar commented on src/components/room-screen/room-screen.jsx
>      <div style={{display: `none`}}>
@vatokato 
Речь SVG спрайт `<div style={{display: `none`}}>...</div>? Он был в разметке.

2021-02-15 09:47 UTC, vatokato commented on src/components/room-screen/room-screen.jsx
>      <div style={{display: `none`}}>
да, насколько я помню - он не нужен. Но если что вернем :)

2021-02-15 10:00 UTC, akzhar commented on src/components/offer-card/offer-card.jsx
> +const OfferCard = ({offer}) => {
Верно я понял?

В отдельном файле хранить проп тайпсы отдельных полей объекта `offer`, а в компонентах их имортировать и объединять в `shape`, если пропс компонента объект или использовать без `shape`, если пропсы компонента отдельные поля объекта?

Отдельный файл хранит только отдельные поля:
```
const offerTypes = {
    ...
    id: PropTypes.number.isRequired,
    bedrooms: PropTypes.number.isRequired,
    city: cityShape.isRequired,
    ...
}
```
В компоненте `OfferCard` использовать так:
```
// в кач-ве пропсов передаются только используемые компонентом поля объекта offer (без деструктуризации)
const OfferCard = (isPremium, header, costEuro) => { ... }; 
...
OfferCard.propTypes = { 
   PropTypes.shape({
      ...
   })
};
```
В родительском компоненте `OffersList`, который просто прокидывает его дочернему компоненту `OfferCard`, и у которого пропсом является объект `offer` целиком, проп тайп уже группирует отдельные поля в `shape`:
```
OffersList.propTypes = {
   offers: PropTypes.arrayOf(
         PropTypes.shape({
            ...
         })
   ).isRequired
};
```

2021-02-15 10:01 UTC, akzhar commented on src/components/offers-list/offers-list.jsx
> +          onPointerEnter={hoverHandler}
Уход мыши = нет активного элемента?

2021-02-15 10:01 UTC, akzhar commented on src/components/offers-list/offers-list.jsx
> +  function hoverHandler(evt) {
Да, забыл про это, хоть и говорили об этом на лайвах.

2021-02-15 10:04 UTC, vatokato commented on src/components/offer-card/offer-card.jsx
> +const OfferCard = ({offer}) => {
да, почти все верно:
1. хранить проп тайпсы полей
```
const offerTypes = {
    ...
    id: PropTypes.number.isRequired,
    bedrooms: PropTypes.number.isRequired,
    city: cityShape.isRequired,
    ...
}
```
2. В компоненте OfferCard использовать так:
```
тут не нужен шейп, все должно работать итак
OfferCard.propTypes = offerTypes;

если нужны доп. поля, то так:
OfferCard.propTypes = {
   ...offerTypes,
   somethingElse: propTypes.string
};
```

3. В листах так:
```
OffersList.propTypes = {
   offers: PropTypes.arrayOf(PropTypes.shape(offerTypes)).isRequired
};
```

2021-02-15 10:10 UTC, vatokato commented on src/components/offers-list/offers-list.jsx
> +          onPointerEnter={hoverHandler}
ага, `setState(null)` или что то такое

2021-02-15 10:18 UTC, akzhar commented on src/components/offers-list/offers-list.jsx
> +        <article className="cities__place-card place-card"
Заколхозил я знатно, конечно...))

2021-02-15 10:19 UTC, akzhar commented on src/components/favorites-screen/favorites-screen.jsx
> +const FavoritesScreen = ({offers}) => { // сейчас выводятся не favorites, а все offers подряд
А почему?

2021-02-15 10:21 UTC, akzhar commented on src/components/app/app.jsx
> +        <FavoritesScreen offers={offers}/>
Это нагляднее при чтении кода?
Или лучше "подготовку" данных делать на уровне `App` (передающего компоненты), а `FavoritesScreen` (принимающий) просто их рендерит?

2021-02-15 10:28 UTC, akzhar commented on src/components/room-screen/room-screen.jsx
> +  const offer = offers.filter((room) => room.id.toString() === id)[0];
Согласен.

2021-02-15 10:30 UTC, vatokato commented on src/components/favorites-screen/favorites-screen.jsx
> +const FavoritesScreen = ({offers}) => { // сейчас выводятся не favorites, а все offers подряд
компонент должен быть максимально простым и выполнять свою главную функцию: отрендерить полученные данные. Если у нас есть возможность вынести логику из конечного компонента - нужно стараться это делать. В будущем всю логику мы будем делать в коннекторе или редьюсере, или экшенах

2021-02-15 10:31 UTC, vatokato commented on src/components/app/app.jsx
> +        <FavoritesScreen offers={offers}/>
да, это нагляднее. Компоненеты должны быть максимально просты. Но если уж по какой-то причине нужно оставлять логику в компонентах(как в нашем случае), то лучше попытаться сосредоточить в одном месте

2021-02-15 13:34 UTC, akzhar commented on src/components/offers-list/offers-list.jsx
> +        <article className="cities__place-card place-card"
Исправлено

2021-02-15 13:41 UTC, akzhar commented on src/components/room-screen/room-screen.jsx
>      <div style={{display: `none`}}>
Убрал, вроде в разметке ничего не сломалось :)

2021-02-15 13:45 UTC, akzhar commented on src/components/offers-list/offers-list.jsx
> +  function hoverHandler(evt) {
Исправил

2021-02-15 13:52 UTC, akzhar commented on src/components/offers-list/offers-list.jsx
> +          onPointerEnter={hoverHandler}
Добавил onMouseEnter и onMouseLeave вместо PointerEnter.
Добавил обработку ухода мыши от карточки.

2021-02-15 13:59 UTC, akzhar commented on src/components/favorites-screen/favorites-screen.jsx
> +const FavoritesScreen = ({offers}) => { // сейчас выводятся не favorites, а все offers подряд
Вынес фильтрацию в `App`

2021-02-15 14:00 UTC, akzhar commented on src/components/app/app.jsx
> +        <FavoritesScreen offers={offers}/>
Фильтрация вынесена в `App` (правда там не offers фильтруются, а из offers получается массив с городами)

2021-02-15 14:13 UTC, akzhar commented on src/components/room-screen/room-screen.jsx
> +  const offer = offers.filter((room) => room.id.toString() === id)[0];
Сделал

2021-02-15 14:33 UTC, akzhar commented on src/components/offer-card/offer-card.jsx
> +const OfferCard = ({offer}) => {
Переписал пропсы

2021-02-16 17:48 UTC, vatokato commented on src/components/favorites-screen/favorites-screen.jsx
> +const FavoritesScreen = ({offers}) => { // сейчас выводятся не favorites, а все offers подряд
не увидел, в FavoritesScreen все еще попадают все offers

2021-02-16 17:56 UTC, vatokato approved these changes

2021-02-16 17:56 UTC, vatokato commented on src/components/offers-list/offers-list.jsx
> +          handleOfferCardHover={handleOfferCardHover}
а вот в `OfferCard` обработчик нужно передавать пропсом `onOfferCardHover` :D
`onOfferCardHover={handleOfferCardHover}`

2021-02-16 18:07 UTC, merged