Module4 task2
htmlacademy-react/490939-six-cities-6 pull request #7
Opened 2021-02-23 20:26 UTC by akzhar

2021-02-24 15:59 UTC, vatokato requested changes
Отлично, особенно с картой.

2021-02-24 15:59 UTC, vatokato commented on src/components/reviews-list/reviews-list.jsx
> +      <ReviewItem key={review.date} review={review}/>
почему `review.date`? лучше уж тогда взять `key` из `map`

и еще:
почему ты передаешь `<ReviewItem review={review} />`?
гораздо логичнее передавать `<ReviewItem {..review} />`
а в компоненте: 
```
const Review = ({id, name ...}) => <div>{id} {name}</div>
```
согласись так нагляднее?

2021-02-24 15:59 UTC, vatokato commented on src/components/room-screen/room-screen.jsx
> +                offersNear.map((offerNear) => {
очень круто, что ты сделал именно так: передаешь в карту только нужные данные.
карта не должна знать ни о каких офферах и чем то там еще :)
молодец

2021-02-24 15:59 UTC, vatokato commented on src/components/room-screen/room-screen.jsx
>            <section className="near-places places">
по заданию нужно вынести эти обертки в отдельные компоненты. 

не особо критично, но я думаю нужно, особенно тот что в `main-screen`

2021-02-24 19:14 UTC, akzhar commented on src/components/reviews-list/reviews-list.jsx
> +      <ReviewItem key={review.date} review={review}/>
С `key` я не прав конечно. На практике `index` из `map` сойдет за `key`?

Все никак не привыкну использовать спред... Соглашусь, что нагляднее.

2021-02-24 19:14 UTC, akzhar commented on src/components/room-screen/room-screen.jsx
> +                offersNear.map((offerNear) => {
Спасибо :)

2021-02-24 19:50 UTC, akzhar commented on src/components/room-screen/room-screen.jsx
>            <section className="near-places places">
Вынес.

Как лучше поступить при отличии в CSS классах у по сути одинаковых компонентов?
Например, у меня компонент `OffersList` используется в 2-х компонентах: `PlacesMain` и `PlacesNear`.
В последнем в качестве пропса `OffersList` передается дополнительный CSS класс.
Что-то мне подсказывает, что это так себе решение...Классов то может быть много разных в других ситуациях...

2021-02-25 02:28 UTC, vatokato commented on src/components/reviews-list/reviews-list.jsx
> +      <ReviewItem key={review.date} review={review}/>
да, это нормально, но только если это не интерактивный элемент (не меняет свое положение в списке), иначе реакт может их попутать :)

2021-02-25 02:34 UTC, vatokato commented on src/components/room-screen/room-screen.jsx
>            <section className="near-places places">
на самом деле это вполне рабочее решение. На практике ты просто не будешь допускать большого различия классов, максимум для контейнера и может для одого двух элементов.

2021-02-25 02:34 UTC, vatokato approved these changes
Отлично! Надеюсь редакс тебе зайдет так же легко

2021-02-25 02:35 UTC, merged